/**
 * Created by pym on 2016/3/22.
 */
define(function(){
    return {
        debug: true,
        webSocket: "ws://localhost:8111/GuPai/gameServer",
        positionCircle : {
            NORTH: "WEST",
            WEST: "SOUTH",
            SOUTH: "EAST",
            EAST: "NORTH"
        },

        cardImages: {
            "WENA": "images/cards/WENA.png",
            "WENAA": "images/cards/WENA.png",
            "WENB": "images/cards/WENB.png",
            "WENBB": "images/cards/WENB.png",
            "WENC": "images/cards/WENC.png",
            "WENCC": "images/cards/WENC.png",
            "WEND": "images/cards/WEND.png",
            "WENDD": "images/cards/WEND.png",
            "WENE": "images/cards/WENE.png",
            "WENEE": "images/cards/WENE.png",
            "WENF": "images/cards/WENF.png",
            "WENFF": "images/cards/WENF.png",
            "WENG": "images/cards/WENG.png",
            "WENGG": "images/cards/WENG.png",
            "WENH": "images/cards/WENH.png",
            "WENHH": "images/cards/WENH.png",
            "WENI": "images/cards/WENI.png",
            "WENII": "images/cards/WENI.png",
            "WENJ": "images/cards/WENJ.png",
            "WENJJ": "images/cards/WENJ.png",
            "WENK": "images/cards/WENK.png",
            "WENKK": "images/cards/WENK.png",
            "WUA": "images/cards/WUA.png",
            "WUAA": "images/cards/WUAA.png",
            "WUB": "images/cards/WUB.png",
            "WUBB": "images/cards/WUBB.png",
            "WUC": "images/cards/WUC.png",
            "WUCC": "images/cards/WUCC.png",
            "WUD": "images/cards/WUD.png",
            "WUE": "images/cards/WUE.png",
            "WUEE": "images/cards/WUEE.png",
            "WUF": "images/cards/WUF.png",

            "WENA_L": "images/cards/WENA_L.png",
            "WENAA_L": "images/cards/WENA_L.png",
            "WENB_L": "images/cards/WENB_L.png",
            "WENBB_L": "images/cards/WENB_L.png",
            "WENC_L": "images/cards/WENC_L.png",
            "WENCC_L": "images/cards/WENC_L.png",
            "WEND_L": "images/cards/WEND_L.png",
            "WENDD_L": "images/cards/WEND_L.png",
            "WENE_L": "images/cards/WENE_L.png",
            "WENEE_L": "images/cards/WENE_L.png",
            "WENF_L": "images/cards/WENF_L.png",
            "WENFF_L": "images/cards/WENF_L.png",
            "WENG_L": "images/cards/WENG_L.png",
            "WENGG_L": "images/cards/WENG_L.png",
            "WENH_L": "images/cards/WENH_L.png",
            "WENHH_L": "images/cards/WENH_L.png",
            "WENI_L": "images/cards/WENI_L.png",
            "WENII_L": "images/cards/WENI_L.png",
            "WENJ_L": "images/cards/WENJ_L.png",
            "WENJJ_L": "images/cards/WENJ_L.png",
            "WENK_L": "images/cards/WENK_L.png",
            "WENKK_L": "images/cards/WENK_L.png",
            "WUA_L": "images/cards/WUA_L.png",
            "WUAA_L": "images/cards/WUAA_L.png",
            "WUB_L": "images/cards/WUB_L.png",
            "WUBB_L": "images/cards/WUBB_L.png",
            "WUC_L": "images/cards/WUC_L.png",
            "WUCC_L": "images/cards/WUCC_L.png",
            "WUD_L": "images/cards/WUD_L.png",
            "WUE_L": "images/cards/WUE_L.png",
            "WUEE_L": "images/cards/WUEE_L.png",
            "WUF_L": "images/cards/WUF_L.png"
        }
    }
});
